version: '3.8'

services:

  emb_opt_server:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - ${EMB_OPT_PORT}:${EMB_OPT_PORT}
    env_file: .env
    environment:
      - CONTAINER_ROLE=server
    depends_on:
      - redis
      - mongo

  worker:
    build:
      context: .
      dockerfile: app.Dockerfile
    env_file: .env
    environment:
      - CONTAINER_ROLE=worker
    depends_on:
      - emb_opt_server

  mock_server:
    profiles:
      - testing
    build:
      context: .
      dockerfile: mock.Dockerfile
    env_file: .env
    ports:
      - ${MOCK_PORT}:${MOCK_PORT}
    depends_on:
      - emb_opt_server

  mongo:
    image: mongo
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
  
  redis:
    image: redis:7
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  dashboard:
    profiles:
      - dashboard
    image: mher/flower
    ports:
      - ${FLOWER_PORT}:${FLOWER_PORT}
    env_file: .env
    command: sh -c "celery --broker=$$CELERY_BROKER_URL flower --port=$$FLOWER_PORT"
    depends_on:
      - redis
