version: '3.8'

services:

  emb_opt_server:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - 7861:7861
    env_file: .env
    environment:
      - CONTAINER_ROLE=server
    depends_on:
      - redis
      - mongo

  worker:
    build:
      context: .
      dockerfile: app.Dockerfile
    env_file: .env
    environment:
      - CONTAINER_ROLE=worker
    depends_on:
      - emb_opt_server

  mock_server:
    profiles:
      - testing
    build:
      context: .
      dockerfile: mock.Dockerfile
    env_file: .env
    ports:
      - 7888:7888
    depends_on:
      - emb_opt_server

  mongo:
    image: mongo
    ports:
      - 27017:27017
  
  redis:
    image: redis:7
    ports:
      - 6379:6379

  dashboard:
    profiles:
      - dashboard
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - 5555:5555
    env_file: .env
    environment:
      - CONTAINER_ROLE=dashboard
    depends_on:
      - redis
